<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees [
       <!ELEMENT employees (employee)+>
       <!ELEMENT employee (firstname , lastname , title , hiredate , phone , email)>
       <!ATTLIST employee xmlns CDATA #FIXED "">
       <!ATTLIST employee id CDATA #REQUIRED>
       <!ELEMENT firstname (#PCDATA)>
       <!ELEMENT lastname (#PCDATA)>
       <!ELEMENT title (#PCDATA)>
       <!ELEMENT hiredate (#PCDATA)>
       <!ELEMENT phone (#PCDATA)>
       <!ELEMENT email (#PCDATA)>
       ]>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="emp.xsd">
       <employee xmlns="" id="385450">
              <firstname>John</firstname>
              <lastname>Muir</lastname>
              <title>Engineer</title>
              <hiredate>October 15, 2005</hiredate>
              <phone>2121234567</phone>
              <email>john_smith@gmail.com</email>
       </employee>
       <employee xmlns="" id="385730">
              <firstname>Christina</firstname>
              <lastname>Aguilera</lastname>
              <title>Manager</title>
              <hiredate>September 1, 2010</hiredate>
              <phone>4157654321</phone>
              <email>christina_johnson_smith@gmail.com</email>
       </employee>
</employees>
